name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1  # Change to your AWS region

      - name: Build, tag, and push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URI=$(aws ecr describe-repositories --repository-names my-node-app --region us-east-1 --output text --query 'repositories[0].repositoryUri')
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker push $REPOSITORY_URI:$IMAGE_TAG
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
